# Generated by Django 6.0.4 on 2026-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='education_level',
            field=models.CharField(blank=True, choices=[('FUNDAMENTAL', 'Ensino Fundamental'), ('MEDIO', 'Ensino Médio'), ('SUPERIOR', 'Ensino Superior')], default='MEDIO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('OUTRO', 'Outro')], default='SOLTEIRO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
