# Generated by Django 6.0.4 on 2026-04-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
