# Generated by Django 6.0.4 on 2026-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_client_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
