# Generated by Django 6.0.4 on 2026-04-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_client_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_value', models.FloatField()),
                ('equipment_value', models.FloatField()),
                ('validity', models.CharField(default='12 meses', max_length=50)),
                ('inverter_brand', models.CharField(max_length=255)),
                ('inverter_quantity', models.IntegerField()),
                ('panels_brand', models.CharField(max_length=255)),
                ('panels_quantity', models.IntegerField()),
                ('due_date', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('beneficiary_units', models.CharField(max_length=255)),
                ('contract_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.client')),
            ],
        ),
    ]
