# Generated by Django 6.0.4 on 2026-04-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='equipment_value_extenso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='inverter_k',
            field=models.CharField(default='XX', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='inverter_warranty',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='marital_status',
            field=models.CharField(default='SOLTEIRO (A)', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='nationality',
            field=models.CharField(default='Brasileiro (a)', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='panels_warranty',
            field=models.CharField(default='25', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='panels_watts',
            field=models.CharField(default='XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_value_extenso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='validity',
            field=models.CharField(default='12 (DOZE) MESES', max_length=50),
        ),
    ]
