# Generated by Django 6.0.4 on 2026-04-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='beneficiary_units',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.CharField(max_length=500),
        ),
    ]
