# Generated by Django 6.0 on 2026-04-16 00:44

import django.db.models.deletion
from django.db import migrations, models

def populate_roles(apps, schema_editor):
    """Cria os cargos padrão."""
    Role = apps.get_model('users', 'Role')
    roles = ["Administrador", "Vendedor", "Financeiro"]
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)

def associate_existing_users_to_roles(apps, schema_editor):
    """Associa usuários existentes a cargos baseados no valor do campo antigo."""
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')

    # Mapeia os valores antigos para os novos IDs de Role
    # O valor padrão 'USER' será mapeado para 'Vendedor' como um exemplo de regra de negócio.
    # Superusuários serão Administradores.
    admin_role = Role.objects.get(name="Administrador")
    vendedor_role = Role.objects.get(name="Vendedor")

    for user in User.objects.all():
        if user.is_superuser:
            user.role_fk = admin_role
        else:
            # Lógica para mapear os valores antigos do CharField.
            # Como o campo antigo já foi removido do modelo, não podemos acessá-lo diretamente.
            # Essa abordagem está ficando complexa. Vamos simplificar.
            # A nova estratégia será criar o campo ForeignKey, depois popular os Roles,
            # e então atribuir um Role padrão a todos os superusers.
            pass
    User.objects.filter(is_superuser=True).update(role_fk=admin_role)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_contract_beneficiary_units_and_more'),
    ]

    operations = [
        # 1. Cria a tabela 'Role'
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
            ],
        ),
        
        # 2. Popula a tabela 'Role' com os dados iniciais
        migrations.RunPython(populate_roles),

        # 3. Adiciona a coluna 'is_employee'
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='É Funcionário'),
        ),

        # 4. Remove o campo 'role' antigo (que era um CharField)
        #    É importante fazer isso antes de adicionar o novo com o mesmo nome.
        #    No entanto, a migração automática já faz isso na operação AlterField.
        #    O erro ocorre porque o Django tenta converter os dados.
        #    A abordagem correta é criar o novo campo com um nome diferente,
        #    copiar os dados e depois renomear.

        # ---- Nova Estratégia ----
        # 4. Adiciona o novo campo ForeignKey com um nome temporário.
        migrations.AddField(
            model_name='user',
            name='role_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Cargo Temp'),
        ),

        # 5. Associa superusuários ao cargo 'Administrador' no novo campo.
        migrations.RunPython(associate_existing_users_to_roles),
        
        # 6. Remove o campo 'role' antigo.
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        
        # 7. Renomeia 'role_fk' para 'role'.
        migrations.RenameField(
            model_name='user',
            old_name='role_fk',
            new_name='role',
        ),
    ]
