# Generated by Django 6.0.4 on 2026-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_contracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
