# Generated by Django 6.0.4 on 2026-04-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_company_professional_alter_user_role_companyphone_and_more'),
        ('users', '0013_contract_extra_data'),
    ]

    operations = [
    ]
