# Generated by Django 6.0.4 on 2026-04-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_fix_contracttemplate_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterheadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Papel Timbrado')),
                ('header_image', models.ImageField(upload_to='wrappers/headers/', verbose_name='Imagem de Cabeçalho')),
                ('footer_image', models.ImageField(upload_to='wrappers/footers/', verbose_name='Imagem de Rodapé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
