# Generated by Django 6.0.4 on 2026-04-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_letterheadtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterheadtemplate',
            name='footer_margin_mm',
            field=models.FloatField(default=5.94, verbose_name='Margem Inferior (mm)'),
        ),
        migrations.AddField(
            model_name='letterheadtemplate',
            name='header_margin_mm',
            field=models.FloatField(default=5.94, verbose_name='Margem Superior (mm)'),
        ),
    ]
