# Generated by Django 6.0.4 on 2026-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_letterheadtemplate_footer_margin_mm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterheadtemplate',
            name='footer_margin_mm',
        ),
        migrations.RemoveField(
            model_name='letterheadtemplate',
            name='header_margin_mm',
        ),
        migrations.AddField(
            model_name='letterheadtemplate',
            name='footer_margin_percent',
            field=models.FloatField(default=2.0, verbose_name='Margem Inferior (%)'),
        ),
        migrations.AddField(
            model_name='letterheadtemplate',
            name='header_margin_percent',
            field=models.FloatField(default=2.0, verbose_name='Margem Superior (%)'),
        ),
    ]
