# Generated by Django 6.0 on 2026-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_letterheadtemplate_footer_margin_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/pdfs/', verbose_name='Arquivo PDF'),
        ),
    ]
