# Generated by Django 6.0 on 2026-04-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_contract_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='beneficiary_units',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='equipment_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='equipment_value_extenso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='inverter_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='inverter_k',
            field=models.CharField(blank=True, default='XX', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='inverter_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='inverter_warranty',
            field=models.CharField(blank=True, default='10', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='marital_status',
            field=models.CharField(blank=True, default='SOLTEIRO (A)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='nationality',
            field=models.CharField(blank=True, default='Brasileiro (a)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='panels_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='panels_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='panels_warranty',
            field=models.CharField(blank=True, default='25', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='panels_watts',
            field=models.CharField(blank=True, default='XXX', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_value_extenso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='validity',
            field=models.CharField(blank=True, default='12 (DOZE) MESES', max_length=50, null=True),
        ),
    ]
