# Generated by Django 6.0 on 2026-04-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_contract_beneficiary_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='equipment_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
