# Generated by Django 6.0.4 on 2026-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Contrato')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador (Slug)')),
                ('conteudo_html', models.TextField(help_text='Use tags Jinja2 como {{ cliente.nome_completo }} para os dados.', verbose_name='Conteúdo HTML (Template Jinja2)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contratos',
            },
        ),
    ]
